configuration:
  configuration_dir: "commons/config"
  template_dir:
    - "commons/templates"
    - ".moban.d"
  configuration: pyexcel.yml
targets:
  - setup.py: setup.py
  - "doc/source/conf.py": "docs/source/conf.py"
  - .travis.yml: travis.yml
  - requirements.txt: requirements.txt
  - "tests/requirements.txt": "tests/requirements.txt"
  - LICENSE: LICENSE.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - README.rst: README.rst
  - "doc/source/guide.rst": "docs/source/guide.rst"