language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
  - 3.4
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install -r requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install -r requirements.txt; fi  
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install -r py3_requirements.txt; fi
  - pip install -r tests/requirements.txt
script:
  nosetests --rednose --with-cov
after_success:
  codecov
