language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - cd tests/test_plugin
  - python setup.py install
  - cd -
script:
  nosetests --rednose --with-cov
after_success:
  codecov
