sudo: false
language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install weakrefset; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then rm tests/test_examples.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then pip install lxml==3.4.4; fi
  - pip install https://github.com/chfw/pyexcel-io/archive/yielding.zip
  - pip install -r tests/requirements.txt
  - pip install -r requirements.txt
script:
  make test
after_success:
  coveralls
